### ISSUE TITLE
Fix potential security vulnerabilities in project dependencies.

### ISSUE THREAD

**Issue by ApoTheOne** [ApoTheOne/PPOC#3]
- [x] node-browser-compat / atob => upgrade from 2.0.3 to 2.1.0
 - [x] unclechu / node-deep-extend deep-extend => upgrade from 0.4.2 to 0.5.1
 - [x] jonschlinkert / randomatic => upgrade from 1.1.7 to 3.0.0

**Comment by Surabhi-Saklani** [comment]
I want to help!
